import { CoupleInputInfo, PersonInputData } from './types';

export const mockPeople: PersonInputData[] = [
  {
    name: 'King George V',
    gender: 'M',
    status: 'king',
    born: '1865',
    death: '1936',
  },
  {
    name: 'Queen Mary',
    gender: 'F',
    status: 'queen',
    born: '1867',
    death: '1953',
  },
  {
    name: 'King Edward VIII',
    gender: 'M',
    status: 'king',
    born: '1894',
    death: '1972',
  },
  {
    name: 'King George VI',
    gender: 'M',
    status: 'king',
    born: '1895',
    death: '1952',
  },
  {
    name: 'The Queen Mother',
    gender: 'F',
    status: 'queen',
    born: '1900',
    death: '2002',
  },
  {
    name: 'Princess Mary, Princess Royal and Countess of Harewood',
    gender: 'F',
    status: 'princess',
    born: '1897',
    death: '1965',
  },
  {
    name: 'Henry George Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1882',
    death: '1947',
  },
  {
    name: 'Prince Henry, Duke of Gloucester',
    gender: 'M',
    status: 'prince',
    born: '1900',
    death: '1974',
  },
  {
    name: 'Princess Alice, Douchess of Gloucester',
    gender: 'F',
    status: 'princess',
    born: '1901',
    death: '2004',
  },
  {
    name: 'Prince George, Duke of Kent',
    gender: 'M',
    status: 'prince',
    born: '1902',
    death: '1942',
  },
  {
    name: 'Princess Marina of Greece and Denmark',
    gender: 'F',
    status: 'princess',
    born: '1906',
    death: '1968',
  },
  {
    name: 'Prince John of the United Kingdom',
    gender: 'M',
    status: 'prince',
    born: '1905',
    death: '1919',
  },
  {
    name: 'Queen Elizabeth II',
    gender: 'F',
    status: 'queen',
    born: '1926',
    death: '2022',
  },
  {
    name: 'Prince Philip, Duke of Edinburgh',
    gender: 'M',
    status: 'prince',
    born: '1921',
    death: '2021',
  },
  {
    name: 'Princess Margaret, Countess of Snowdon',
    gender: 'F',
    status: 'princess',
    born: '1930',
    death: '2002',
  },
  {
    name: 'Anthony Armstrong-Jones',
    gender: 'M',
    status: 'civilian',
    born: '1930',
    death: '2017',
  },
  {
    name: 'George Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1923',
    death: '2011',
  },
  {
    name: 'Patricia Tuckwell',
    gender: 'F',
    status: 'civilian',
    born: '1926',
    death: '2018',
  },
  {
    name: 'Marion Stein',
    gender: 'F',
    status: 'civilian',
    born: '1926',
    death: '2014',
  },
  {
    name: 'Gerald Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1924',
    death: '1998',
  },
  {
    name: 'Elizabeth Colvin',
    gender: 'F',
    status: 'civilian',
    born: '1924',
    death: '2006',
  },
  {
    name: 'Angela Dowding',
    gender: 'F',
    status: 'civilian',
    born: '1919',
    death: '2007',
  },
  {
    name: 'Prince William of Gloucester',
    gender: 'M',
    status: 'prince',
    born: '1941',
    death: '1972',
  },
  {
    name: 'Prince Richard, Duke of Gloucester',
    gender: 'M',
    status: 'prince',
    born: '1944',
    death: null,
  },
  {
    name: 'Birgitte van Deurs Henriksen',
    gender: 'F',
    status: 'civilian',
    born: '1946',
    death: null,
  },
  {
    name: 'Prince Edward, Duke of Kent',
    gender: 'M',
    status: 'prince',
    born: '1935',
    death: null,
  },
  {
    name: 'Katrina Worsley',
    gender: 'F',
    status: 'civilian',
    born: '1933',
    death: null,
  },
  {
    name: 'Princess Alexandra, The Honourable Lady Ogilvy',
    gender: 'F',
    status: 'princess',
    born: '1936',
    death: null,
  },
  {
    name: 'Angus Ogilvy',
    gender: 'M',
    status: 'civilian',
    born: '1928',
    death: '2004',
  },
  {
    name: 'Prince Michael of Kent',
    gender: 'M',
    status: 'prince',
    born: '1942',
    death: null,
  },
  {
    name: 'Marie Christine von Reibnitz',
    gender: 'F',
    status: 'civilian',
    born: '1945',
    death: null,
  },
  {
    name: 'King Charles III',
    gender: 'M',
    status: 'king',
    born: '1948',
    death: null,
  },
  {
    name: 'Camilla Queen Consort',
    gender: 'F',
    status: 'queen',
    born: '1947',
    death: null,
  },
  {
    name: 'Princess Diana of Wales',
    gender: 'F',
    status: 'princess',
    born: '1961',
    death: '1997',
  },
  {
    name: 'Princess Anne, Princess Royal',
    gender: 'F',
    status: 'princess',
    born: '1950',
    death: null,
  },
  {
    name: 'Timothy Laurence',
    gender: 'M',
    status: 'civilian',
    born: '1955',
    death: null,
  },
  {
    name: 'Mark Phillips',
    gender: 'M',
    status: 'civilian',
    born: '1948',
    death: null,
  },
  {
    name: 'Prince Andrew, Duke of York',
    gender: 'M',
    status: 'prince',
    born: '1960',
    death: null,
  },
  {
    name: 'Sarah Ferguson',
    gender: 'F',
    status: 'civilian',
    born: '1959',
    death: null,
  },
  {
    name: 'Prince Edward, Duke of Edinburgh',
    gender: 'M',
    status: 'prince',
    born: '1964',
    death: null,
  },
  {
    name: 'Sophie, Duchess of Edinburgh',
    gender: 'F',
    status: 'civilian',
    born: '1965',
    death: null,
  },
  {
    name: 'David Armstrong-Jones, 2nd Earl of Snowdon',
    gender: 'M',
    status: 'prince',
    born: '1961',
    death: null,
  },
  {
    name: 'Serena Alleyne Stanhope',
    gender: 'F',
    status: 'civilian',
    born: '1970',
    death: null,
  },
  {
    name: 'Lady Sarah Chatto Armstrong-Jones',
    gender: 'F',
    status: 'princess',
    born: '1964',
    death: null,
  },
  {
    name: 'Daniel St George Chatto',
    gender: 'M',
    status: 'civilian',
    born: '1957',
    death: null,
  },
  {
    name: 'David Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1950',
    death: null,
  },
  {
    name: 'Margaret Rosalind Messenger',
    gender: 'F',
    status: 'civilian',
    born: '1948',
    death: null,
  },
  {
    name: 'James Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1953',
    death: null,
  },
  {
    name: 'Joy Elias-Rilwan',
    gender: 'F',
    status: 'civilian',
    born: '1954',
    death: null,
  },
  {
    name: 'Lorie Susan Lee',
    gender: 'F',
    status: 'civilian',
    born: '1954',
    death: '2001',
  },
  {
    name: 'Frederica Ann Duhrssen',
    gender: 'F',
    status: 'civilian',
    born: '1954',
    death: null,
  },
  {
    name: 'Jeremy Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1955',
    death: null,
  },
  {
    name: 'Catherine Isobel Bell',
    gender: 'F',
    status: 'civilian',
    born: '1964',
    death: null,
  },
  {
    name: 'Julie Bayliss',
    gender: 'F',
    status: 'civilian',
    born: '1957',
    death: null,
  },
  {
    name: 'Mark Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1964',
    death: null,
  },
  {
    name: 'Andrea Kershaw',
    gender: 'F',
    status: 'civilian',
    born: '1964',
    death: null,
  },
  {
    name: 'Judith Kilburn',
    gender: 'F',
    status: 'civilian',
    born: '1958',
    death: null,
  },
  {
    name: 'Martin David Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1962',
    death: null,
  },
  {
    name: 'Charmaine Eccleston',
    gender: 'F',
    status: 'civilian',
    born: '1962',
    death: null,
  },
  {
    name: 'Henry Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1953',
    death: null,
  },
  {
    name: 'Fiona Wilmott',
    gender: 'F',
    status: 'civilian',
    born: null,
    death: null,
  },
  {
    name: 'Alexandra Morton',
    gender: 'F',
    status: 'civilian',
    born: null,
    death: null,
  },
  {
    name: 'Alexander Windsor, Earl of Ulster',
    gender: 'M',
    status: 'civilian',
    born: '1974',
    death: null,
  },
  {
    name: 'Claire Booth',
    gender: 'F',
    status: 'civilian',
    born: null,
    death: null,
  },
  {
    name: 'Lady Davina Lewis',
    gender: 'F',
    status: 'civilian',
    born: '1977',
    death: null,
  },
  {
    name: 'Gary Lewis',
    gender: 'M',
    status: 'civilian',
    born: null,
    death: null,
  },
  {
    name: 'Lady Rose Gilman',
    gender: 'F',
    status: 'civilian',
    born: '1980',
    death: null,
  },
  {
    name: 'George Gilman',
    gender: 'M',
    status: 'civilian',
    born: null,
    death: null,
  },
  {
    name: 'George Windsor',
    gender: 'M',
    status: 'civilian',
    born: '1962',
    death: null,
  },
  {
    name: 'Sylvana Tomaselli',
    gender: 'F',
    status: 'civilian',
    born: '1957',
    death: null,
  },
  {
    name: 'Lady Helen Taylor',
    gender: 'F',
    status: 'civilian',
    born: '1964',
    death: null,
  },
  {
    name: 'Timothy Vernon Taylor',
    gender: 'M',
    status: 'civilian',
    born: null,
    death: null,
  },
  {
    name: 'Lord Nicholas Windsor',
    gender: 'M',
    status: 'civilian',
    born: '1970',
    death: null,
  },
  {
    name: 'Lady Nicholas Windsor',
    gender: 'F',
    status: 'civilian',
    born: '1969',
    death: null,
  },
  {
    name: 'James Ogilvy',
    gender: 'M',
    status: 'civilian',
    born: '1964',
    death: null,
  },
  {
    name: 'Julia Rawlinson',
    gender: 'F',
    status: 'civilian',
    born: null,
    death: null,
  },
  {
    name: 'Marina Ogilvy',
    gender: 'F',
    status: 'civilian',
    born: '1966',
    death: null,
  },
  {
    name: 'Paul Mowatt',
    gender: 'M',
    status: 'civilian',
    born: null,
    death: null,
  },
  {
    name: 'Lord Frederick Windsor',
    gender: 'M',
    status: 'civilian',
    born: '1979',
    death: null,
  },
  {
    name: 'Sophie Winkleman',
    gender: 'F',
    status: 'civilian',
    born: '1980',
    death: null,
  },
  {
    name: 'Lady Gabriella Windsor',
    gender: 'F',
    status: 'civilian',
    born: '1981',
    death: null,
  },
  {
    name: 'Thomas Kingston',
    gender: 'M',
    status: 'civilian',
    born: null,
    death: null,
  },
  {
    name: 'Prince William, Prince of Wales',
    gender: 'M',
    status: 'prince',
    born: '1982',
    death: null,
  },
  {
    name: 'Catherine Princess of Wales',
    gender: 'F',
    status: 'princess',
    born: '1982',
    death: null,
  },
  {
    name: 'Prince Harry, Duke of Sussex',
    gender: 'M',
    status: 'prince',
    born: '1984',
    death: null,
  },
  {
    name: 'Meghan Duchess of Sussex',
    gender: 'F',
    status: 'civilian',
    born: '1981',
    death: null,
  },
  {
    name: 'Peter Phillips',
    gender: 'M',
    status: 'civilian',
    born: '1977',
    death: null,
  },
  {
    name: 'Autumn Kelly',
    gender: 'F',
    status: 'civilian',
    born: '1978',
    death: null,
  },
  {
    name: 'Zara Phillips',
    gender: 'F',
    status: 'civilian',
    born: '1981',
    death: null,
  },
  {
    name: 'Michael Tindall',
    gender: 'M',
    status: 'civilian',
    born: '1977',
    death: null,
  },
  {
    name: 'Princess Beatrice of York',
    gender: 'F',
    status: 'princess',
    born: '1988',
    death: null,
  },
  {
    name: 'Edoardo Mapelli Mozzi',
    gender: 'M',
    status: 'civilian',
    born: '1983',
    death: null,
  },
  {
    name: 'Princess Eugenie of York',
    gender: 'F',
    status: 'princess',
    born: '1990',
    death: null,
  },
  {
    name: 'Jack Brooksbank',
    gender: 'M',
    status: 'civilian',
    born: '1986',
    death: null,
  },
  {
    name: 'Lady Louise Windsor',
    gender: 'F',
    status: 'civilian',
    born: '2003',
    death: null,
  },
  {
    name: 'James Viscount Severn, Earl of Wessex',
    gender: 'M',
    status: 'prince',
    born: '2007',
    death: null,
  },
  {
    name: 'Charles Patrick Inigo',
    gender: 'M',
    status: 'civilian',
    born: '1999',
    death: null,
  },
  {
    name: 'Margarita Elizabeth Rose Alleyne',
    gender: 'F',
    status: 'civilian',
    born: '2002',
    death: null,
  },
  {
    name: 'Samuel Chatto',
    gender: 'M',
    status: 'civilian',
    born: '1996',
    death: null,
  },
  {
    name: 'Arthur Chatto',
    gender: 'M',
    status: 'civilian',
    born: '1999',
    death: null,
  },
  {
    name: 'Emily Shard',
    gender: 'F',
    status: 'civilian',
    born: '1975',
    death: null,
  },
  {
    name: 'Benjamin Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1978',
    death: null,
  },
  {
    name: 'Alexander Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1980',
    death: null,
  },
  {
    name: 'Edward Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1982',
    death: null,
  },
  {
    name: 'Tanit Lascelles',
    gender: 'F',
    status: 'civilian',
    born: '1981',
    death: null,
  },
  {
    name: 'Tewa Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1985',
    death: null,
  },
  {
    name: 'Sophie Lascelles',
    gender: 'F',
    status: 'civilian',
    born: '1973',
    death: null,
  },
  {
    name: 'Rowan Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1977',
    death: null,
  },
  {
    name: 'Tallulah Lascelles',
    gender: 'F',
    status: 'civilian',
    born: '2005',
    death: null,
  },
  {
    name: 'Thomas Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1982',
    death: null,
  },
  {
    name: 'Ellen Lascelles',
    gender: 'F',
    status: 'civilian',
    born: '1984',
    death: null,
  },
  {
    name: 'Amy Lascelles',
    gender: 'F',
    status: 'civilian',
    born: '1986',
    death: null,
  },
  {
    name: 'Charlotte Lascelles',
    gender: 'F',
    status: 'civilian',
    born: '1996',
    death: null,
  },
  {
    name: 'Imogen Lascelles',
    gender: 'F',
    status: 'civilian',
    born: '1998',
    death: null,
  },
  {
    name: 'Miranda Lascelles',
    gender: 'F',
    status: 'civilian',
    born: '2000',
    death: null,
  },
  {
    name: 'Alexandre Joshua Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1996',
    death: null,
  },
  {
    name: 'Maximillian David Lascelles',
    gender: 'M',
    status: 'civilian',
    born: '1991',
    death: null,
  },
  {
    name: 'Xan Windsor',
    gender: 'M',
    status: 'civilian',
    born: '2007',
    death: null,
  },
  {
    name: 'Lady Cosima Windsor',
    gender: 'F',
    status: 'civilian',
    born: '2010',
    death: null,
  },
  {
    name: 'Senna Lewis',
    gender: 'F',
    status: 'civilian',
    born: '2010',
    death: null,
  },
  {
    name: 'Lyla Gilman',
    gender: 'F',
    status: 'civilian',
    born: '2010',
    death: null,
  },
  {
    name: 'Edward Windsor',
    gender: 'M',
    status: 'civilian',
    born: '1988',
    death: null,
  },
  {
    name: 'Lady Marina-Charlotte Windsor',
    gender: 'F',
    status: 'civilian',
    born: '1992',
    death: null,
  },
  {
    name: 'Lady Amelia Windsor',
    gender: 'F',
    status: 'civilian',
    born: '1995',
    death: null,
  },
  {
    name: 'Columbus Taylor',
    gender: 'M',
    status: 'civilian',
    born: '1994',
    death: null,
  },
  {
    name: 'Cassius Taylor',
    gender: 'M',
    status: 'civilian',
    born: '1996',
    death: null,
  },
  {
    name: 'Eloise Taylor',
    gender: 'F',
    status: 'civilian',
    born: '2003',
    death: null,
  },
  {
    name: 'Estella Taylor',
    gender: 'F',
    status: 'civilian',
    born: '2004',
    death: null,
  },
  {
    name: 'Albert Windsor',
    gender: 'M',
    status: 'civilian',
    born: '2007',
    death: null,
  },
  {
    name: 'Leopold Windsor',
    gender: 'M',
    status: 'civilian',
    born: '2009',
    death: null,
  },
  {
    name: 'Flora Ogilvy',
    gender: 'F',
    status: 'civilian',
    born: '1994',
    death: null,
  },
  {
    name: 'Timothy Vesterberg',
    gender: 'M',
    status: 'civilian',
    born: '1993',
    death: null,
  },
  {
    name: 'Alexander Ogilvy',
    gender: 'M',
    status: 'civilian',
    born: '1996',
    death: null,
  },
  {
    name: 'Zenouska Mowatt',
    gender: 'F',
    status: 'civilian',
    born: '1990',
    death: null,
  },
  {
    name: 'Christian Mowatt',
    gender: 'M',
    status: 'civilian',
    born: '1993',
    death: null,
  },
  {
    name: 'Prince George of Wales',
    gender: 'M',
    status: 'prince',
    born: '2013',
    death: null,
  },
  {
    name: 'Princess Charlotte of Wales',
    gender: 'F',
    status: 'princess',
    born: '2015',
    death: null,
  },
  {
    name: 'Prince Louis of Wales',
    gender: 'M',
    status: 'prince',
    born: '2018',
    death: null,
  },
  {
    name: 'Prince Archie of Sussex',
    gender: 'M',
    status: 'prince',
    born: '2019',
    death: null,
  },
  {
    name: 'Princess Lilibet of Sussex',
    gender: 'F',
    status: 'princess',
    born: '2021',
    death: null,
  },
  {
    name: 'Savannah Anne Kathleen Phillips',
    gender: 'F',
    status: 'civilian',
    born: '2010',
    death: null,
  },
  {
    name: 'Isla Elizabeth Phillips',
    gender: 'F',
    status: 'civilian',
    born: '2012',
    death: null,
  },
  {
    name: 'Mia Grace Tindall',
    gender: 'F',
    status: 'civilian',
    born: '2014',
    death: null,
  },
  {
    name: 'Lena Elizabeth Tindall',
    gender: 'F',
    status: 'civilian',
    born: '2018',
    death: null,
  },
  {
    name: 'Lucas Philip Tindall',
    gender: 'M',
    status: 'civilian',
    born: '2021',
    death: null,
  },
  {
    name: 'Sienna Mapeli Mozzi',
    gender: 'F',
    status: 'civilian',
    born: '2021',
    death: null,
  },
  {
    name: 'August Brooksbank',
    gender: 'M',
    status: 'civilian',
    born: '2021',
    death: null,
  },
  {
    name: 'Ernest Brooksbank',
    gender: 'M',
    status: 'civilian',
    born: '2023',
    death: null,
  },
];

export const mockCoupleInfo: CoupleInputInfo[] = [
  {
    spouses: ['King George V', 'Queen Mary'],
    children: [
      'King Edward VIII',
      'King George VI',
      'Princess Mary, Princess Royal and Countess of Harewood',
      'Prince Henry, Duke of Gloucester',
      'Prince George, Duke of Kent',
      'Prince John of the United Kingdom',
    ],
    dotted: false,
  },
  {
    spouses: ['King George VI', 'The Queen Mother'],
    children: ['Queen Elizabeth II', 'Princess Margaret, Countess of Snowdon'],
    dotted: false,
  },
  {
    spouses: [
      'Princess Mary, Princess Royal and Countess of Harewood',
      'Henry George Lascelles',
    ],
    children: ['George Lascelles', 'Gerald Lascelles'],
    dotted: false,
  },
  {
    spouses: [
      'Prince Henry, Duke of Gloucester',
      'Princess Alice, Douchess of Gloucester',
    ],
    children: [
      'Prince Richard, Duke of Gloucester',
      'Prince William of Gloucester',
    ],
    dotted: false,
  },
  {
    spouses: [
      'Prince George, Duke of Kent',
      'Princess Marina of Greece and Denmark',
    ],
    children: [
      'Prince Edward, Duke of Kent',
      'Princess Alexandra, The Honourable Lady Ogilvy',
      'Prince Michael of Kent',
    ],
    dotted: false,
  },
  {
    spouses: ['Queen Elizabeth II', 'Prince Philip, Duke of Edinburgh'],
    children: [
      'King Charles III',
      'Princess Anne, Princess Royal',
      'Prince Andrew, Duke of York',
      'Prince Edward, Duke of Edinburgh',
    ],
    dotted: false,
  },
  {
    spouses: [
      'Princess Margaret, Countess of Snowdon',
      'Anthony Armstrong-Jones',
    ],
    children: [
      'David Armstrong-Jones, 2nd Earl of Snowdon',
      'Lady Sarah Chatto Armstrong-Jones',
    ],
    dotted: true,
  },
  {
    spouses: ['George Lascelles', 'Patricia Tuckwell'],
    children: [],
    dotted: false,
  },
  {
    spouses: ['George Lascelles', 'Marion Stein'],
    children: [
      'David Lascelles',
      'James Lascelles',
      'Jeremy Lascelles',
      'Mark Lascelles',
    ],
    dotted: true,
  },
  {
    spouses: ['Gerald Lascelles', 'Elizabeth Colvin'],
    children: ['Martin David Lascelles'],
    dotted: false,
  },
  {
    spouses: ['Gerald Lascelles', 'Angela Dowding'],
    children: ['Henry Lascelles'],
    dotted: true,
  },
  {
    spouses: [
      'Prince Richard, Duke of Gloucester',
      'Birgitte van Deurs Henriksen',
    ],
    children: [
      'Alexander Windsor, Earl of Ulster',
      'Lady Davina Lewis',
      'Lady Rose Gilman',
    ],
    dotted: false,
  },
  {
    spouses: ['Prince Edward, Duke of Kent', 'Katrina Worsley'],
    children: ['George Windsor', 'Lady Helen Taylor', 'Lord Nicholas Windsor'],
    dotted: false,
  },
  {
    spouses: ['Princess Alexandra, The Honourable Lady Ogilvy', 'Angus Ogilvy'],
    children: ['James Ogilvy', 'Marina Ogilvy'],
    dotted: false,
  },
  {
    spouses: ['Prince Michael of Kent', 'Marie Christine von Reibnitz'],
    children: ['Lord Frederick Windsor', 'Lady Gabriella Windsor'],
    dotted: false,
  },
  {
    spouses: ['King Charles III', 'Camilla Queen Consort'],
    children: [],
    dotted: false,
  },
  {
    spouses: ['King Charles III', 'Princess Diana of Wales'],
    children: [
      'Prince William, Prince of Wales',
      'Prince Harry, Duke of Sussex',
    ],
    dotted: true,
  },
  {
    spouses: ['Princess Anne, Princess Royal', 'Timothy Laurence'],
    children: [],
    dotted: false,
  },
  {
    spouses: ['Princess Anne, Princess Royal', 'Mark Phillips'],
    children: ['Peter Phillips', 'Zara Phillips'],
    dotted: true,
  },
  {
    spouses: ['Prince Andrew, Duke of York', 'Sarah Ferguson'],
    children: ['Princess Beatrice of York', 'Princess Eugenie of York'],
    dotted: false,
  },
  {
    spouses: [
      'Prince Edward, Duke of Edinburgh',
      'Sophie, Duchess of Edinburgh',
    ],
    children: ['Lady Louise Windsor', 'James Viscount Severn, Earl of Wessex'],
    dotted: false,
  },
  {
    spouses: [
      'David Armstrong-Jones, 2nd Earl of Snowdon',
      'Serena Alleyne Stanhope',
    ],
    children: ['Charles Patrick Inigo', 'Margarita Elizabeth Rose Alleyne'],
    dotted: true,
  },
  {
    spouses: ['Lady Sarah Chatto Armstrong-Jones', 'Daniel St George Chatto'],
    children: ['Samuel Chatto', 'Arthur Chatto'],
    dotted: false,
  },
  {
    spouses: ['David Lascelles', 'Margaret Rosalind Messenger'],
    children: [
      'Emily Shard',
      'Benjamin Lascelles',
      'Alexander Lascelles',
      'Edward Lascelles',
    ],
    dotted: false,
  },
  {
    spouses: ['James Lascelles', 'Joy Elias-Rilwan'],
    children: [],
    dotted: false,
  },
  {
    spouses: ['James Lascelles', 'Lorie Susan Lee'],
    children: ['Tanit Lascelles', 'Tewa Lascelles'],
    dotted: true,
  },
  {
    spouses: ['James Lascelles', 'Frederica Ann Duhrssen'],
    children: ['Sophie Lascelles', 'Rowan Lascelles'],
    dotted: true,
  },
  {
    spouses: ['Jeremy Lascelles', 'Catherine Isobel Bell'],
    children: ['Tallulah Lascelles'],
    dotted: false,
  },
  {
    spouses: ['Jeremy Lascelles', 'Julie Bayliss'],
    children: ['Thomas Lascelles', 'Ellen Lascelles', 'Amy Lascelles'],
    dotted: true,
  },
  {
    spouses: ['Mark Lascelles', 'Andrea Kershaw'],
    children: ['Charlotte Lascelles', 'Imogen Lascelles', 'Miranda Lascelles'],
    dotted: true,
  },
  {
    spouses: ['Mark Lascelles', 'Judith Kilburn'],
    children: [],
    dotted: false,
  },
  {
    spouses: ['Martin David Lascelles', 'Charmaine Eccleston'],
    children: ['Alexandre Joshua Lascelles'],
    dotted: false,
  },
  {
    spouses: ['Henry Lascelles', 'Fiona Wilmott'],
    children: [],
    dotted: false,
  },
  {
    spouses: ['Henry Lascelles', 'Alexandra Morton'],
    children: ['Maximillian David Lascelles'],
    dotted: true,
  },
  {
    spouses: ['Alexander Windsor, Earl of Ulster', 'Claire Booth'],
    children: ['Xan Windsor', 'Lady Cosima Windsor'],
    dotted: false,
  },
  {
    spouses: ['Lady Davina Lewis', 'Gary Lewis'],
    children: ['Senna Lewis'],
    dotted: true,
  },
  {
    spouses: ['Lady Rose Gilman', 'George Gilman'],
    children: ['Lyla Gilman'],
    dotted: false,
  },
  {
    spouses: ['George Windsor', 'Sylvana Tomaselli'],
    children: [
      'Edward Windsor',
      'Lady Marina-Charlotte Windsor',
      'Lady Amelia Windsor',
    ],
    dotted: false,
  },
  {
    spouses: ['Lady Helen Taylor', 'Timothy Vernon Taylor'],
    children: [
      'Columbus Taylor',
      'Cassius Taylor',
      'Eloise Taylor',
      'Estella Taylor',
    ],
    dotted: false,
  },
  {
    spouses: ['Lord Nicholas Windsor', 'Lady Nicholas Windsor'],
    children: ['Albert Windsor', 'Leopold Windsor'],
    dotted: false,
  },
  {
    spouses: ['James Ogilvy', 'Julia Rawlinson'],
    children: ['Flora Ogilvy', 'Alexander Ogilvy'],
    dotted: false,
  },
  {
    spouses: ['Marina Ogilvy', 'Paul Mowatt'],
    children: ['Zenouska Mowatt', 'Christian Mowatt'],
    dotted: false,
  },
  {
    spouses: ['Lord Frederick Windsor', 'Sophie Winkleman'],
    children: [],
    dotted: false,
  },
  {
    spouses: ['Lady Gabriella Windsor', 'Thomas Kingston'],
    children: [],
    dotted: false,
  },
  {
    spouses: ['Prince William, Prince of Wales', 'Catherine Princess of Wales'],
    children: [
      'Prince George of Wales',
      'Princess Charlotte of Wales',
      'Prince Louis of Wales',
    ],
    dotted: false,
  },
  {
    spouses: ['Prince Harry, Duke of Sussex', 'Meghan Duchess of Sussex'],
    children: ['Prince Archie of Sussex', 'Princess Lilibet of Sussex'],
    dotted: false,
  },
  {
    spouses: ['Peter Phillips', 'Autumn Kelly'],
    children: ['Savannah Anne Kathleen Phillips', 'Isla Elizabeth Phillips'],
    dotted: false,
  },
  {
    spouses: ['Zara Phillips', 'Michael Tindall'],
    children: [
      'Mia Grace Tindall',
      'Lena Elizabeth Tindall',
      'Lucas Philip Tindall',
    ],
    dotted: false,
  },
  {
    spouses: ['Princess Beatrice of York', 'Edoardo Mapelli Mozzi'],
    children: ['Sienna Mapeli Mozzi'],
    dotted: false,
  },
  {
    spouses: ['Princess Eugenie of York', 'Jack Brooksbank'],
    children: ['August Brooksbank', 'Ernest Brooksbank'],
    dotted: false,
  },
  {
    spouses: ['Flora Ogilvy', 'Timothy Vesterberg'],
    children: [],
    dotted: false,
  },
];
